# travis-ci.org build & test configuration
language: cpp

compiler:
  - clang
  - gcc

env:
  matrix:
    - ROOT=5-34-25
    - ROOT=6-02-04
  global:
    - CLANG_VERSION=3.7
    - GCC_VERSION=4.9
    - BOOST_VERSION=1.55

before_install: source ci/before_install.sh
install: source ci/install.sh
script: bash ci/test.sh
cache:
  directories: # also works for files ;)
  - root_v5-34-25_python_2.7.tar.gz
  - root_v6-02-04_python_2.7.tar.gz
